name: Build and Deploy to GCR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          service_account: 'github-actions@github-test-project-442816.iam.gserviceaccount.com'
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: github-test-project-442816
          
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Authenticate Docker with Artifact Registry
        run: gcloud auth configure-docker europe-west9-docker.pkg.dev

      - name: Build Docker Image
        run: docker build -t europe-west9-docker.pkg.dev/github-test-project-442816/myrepo/hello-world:$GITHUB_SHA .

      - name: Push Docker Image
        run: docker push europe-west9-docker.pkg.dev/github-test-project-442816/myrepo/hello-world:$GITHUB_SHA

