name: Build and Deploy to GCR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  PROJECT_ID: 'github-test-project-442816'
  REPO_NAME: 'myrepo'
  IMAGE_NAME: 'hello-world'
  SERVICE_ACCOUNT: 'github-actions@github-test-project-442816.iam.gserviceaccount.com'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/776737377276/locations/global/workloadIdentityPools/gitpool/providers/myrepo'
  REGION: europe-west9
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debug
        run: |
          echo "SERVICE_ACCOUNT=${{ env.SERVICE_ACCOUNT }}"
          echo "WORKLOAD_IDENTITY_PROVIDER=${{ env.WORKLOAD_IDENTITY_PROVIDER }}"
          echo "ID-TOKEN: ${{ github.token }}"
          
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
#         credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          service_account: ${{ env.SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: ${{ env.PROJECT_ID }}
          
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Authenticate Docker with Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:$GITHUB_SHA .

      - name: Push Docker Image
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy hello-service \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:$GITHUB_SHA \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated
            
      - name: Verify Deployment
        run: gcloud run services list --region ${{ env.REGION }}

